server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-courses
    username: postgres
    password: 4278
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        jdbc.lob.non_contextual_creation: true
